// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R54_M11_Class_05_Work_01.Models;

#nullable disable

namespace R54_M11_Class_05_Work_01.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20231007110356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R54_M11_Class_05_Work_01.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool?>("OnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Picture = "1jpg",
                            Price = 1563m,
                            ProductName = "Product 1",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 2,
                            Picture = "2jpg",
                            Price = 1695m,
                            ProductName = "Product 2",
                            Size = 4
                        },
                        new
                        {
                            ProductId = 3,
                            Picture = "3jpg",
                            Price = 1791m,
                            ProductName = "Product 3",
                            Size = 4
                        },
                        new
                        {
                            ProductId = 4,
                            Picture = "4jpg",
                            Price = 1606m,
                            ProductName = "Product 4",
                            Size = 4
                        },
                        new
                        {
                            ProductId = 5,
                            Picture = "5jpg",
                            Price = 1233m,
                            ProductName = "Product 5",
                            Size = 1
                        });
                });

            modelBuilder.Entity("R54_M11_Class_05_Work_01.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            Date = new DateTime(2022, 6, 4, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8831),
                            ProductId = 1,
                            Quantity = 100
                        },
                        new
                        {
                            SaleId = 2,
                            Date = new DateTime(2022, 8, 19, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8865),
                            ProductId = 2,
                            Quantity = 114
                        },
                        new
                        {
                            SaleId = 3,
                            Date = new DateTime(2022, 6, 15, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8876),
                            ProductId = 3,
                            Quantity = 119
                        },
                        new
                        {
                            SaleId = 4,
                            Date = new DateTime(2022, 7, 7, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8885),
                            ProductId = 4,
                            Quantity = 138
                        },
                        new
                        {
                            SaleId = 5,
                            Date = new DateTime(2022, 7, 6, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8895),
                            ProductId = 5,
                            Quantity = 147
                        },
                        new
                        {
                            SaleId = 6,
                            Date = new DateTime(2022, 6, 23, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8905),
                            ProductId = 1,
                            Quantity = 127
                        },
                        new
                        {
                            SaleId = 7,
                            Date = new DateTime(2022, 8, 12, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8915),
                            ProductId = 2,
                            Quantity = 156
                        },
                        new
                        {
                            SaleId = 8,
                            Date = new DateTime(2022, 8, 29, 17, 3, 56, 308, DateTimeKind.Local).AddTicks(8925),
                            ProductId = 3,
                            Quantity = 121
                        });
                });

            modelBuilder.Entity("R54_M11_Class_05_Work_01.Models.Sale", b =>
                {
                    b.HasOne("R54_M11_Class_05_Work_01.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("R54_M11_Class_05_Work_01.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
